/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package intellij.test.state.reproducer;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertEquals(classUnderTest.getGreeting(), "Hello World!");
    }

    @Test void appHasAGreeting1() {
        App classUnderTest = new App();
        assertEquals(classUnderTest.getGreeting(), "Hello World!");
    }

    @Test void appHasAGreeting2() {
        App classUnderTest = new App();
        assertEquals(classUnderTest.getGreeting(), "Hello World!");
    }
}
